package PagarCotes;


/**
* PagarCotes/pagarPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PagarCotes.idl
* jueves 17 de octubre de 2019 10:08:12 PM BOT
*/

public abstract class pagarPOA extends org.omg.PortableServer.Servant
 implements PagarCotes.pagarOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("pagar", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PagarCotes/pagar/pagar
       {
         String idCliente = in.read_string ();
         String $result = null;
         $result = this.pagar (idCliente);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // PagarCotes/pagar/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PagarCotes/pagar:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public pagar _this() 
  {
    return pagarHelper.narrow(
    super._this_object());
  }

  public pagar _this(org.omg.CORBA.ORB orb) 
  {
    return pagarHelper.narrow(
    super._this_object(orb));
  }


} // class pagarPOA
