package PagarCotes;

/**
* PagarCotes/pagarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PagarCotes.idl
* jueves 17 de octubre de 2019 10:08:12 PM BOT
*/

public final class pagarHolder implements org.omg.CORBA.portable.Streamable
{
  public PagarCotes.pagar value = null;

  public pagarHolder ()
  {
  }

  public pagarHolder (PagarCotes.pagar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PagarCotes.pagarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PagarCotes.pagarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PagarCotes.pagarHelper.type ();
  }

}
