package PagarCotes;


/**
* PagarCotes/pagar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PagarCotes.idl
* jueves 17 de octubre de 2019 10:08:12 PM BOT
*/

public interface pagar extends pagarOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface pagar
